// Fase 5.11 — Seed de roles base del sistema
// Requires Fase 5.10 permissions to be seeded first.

const now = new Date();

const roles = [
  {
    "_id": "role_platform_super_admin",
    "code": "platform_super_admin",
    "organizationId": null,
    "scope": "platform",
    "type": "system",
    "name": "Platform Super Admin",
    "description": "Control total de plataforma. Uso extremadamente restringido.",
    "permissionKeys": [
      "*"
    ],
    "systemRole": true,
    "critical": true,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_platform_support",
    "code": "platform_support",
    "organizationId": null,
    "scope": "platform",
    "type": "system",
    "name": "Platform Support",
    "description": "Soporte operativo de plataforma sin control total destructivo.",
    "permissionKeys": [
      "organization.view",
      "organization.members.view",
      "credentials.users.view",
      "credentials.sessions.revoke",
      "credentials.roles.view",
      "branches.view",
      "settings.branches.view",
      "settings.emission_points.view",
      "catalog.view",
      "catalog.local.view",
      "catalog.identifiers.verify_master",
      "catalog.identifiers.resolve_conflict",
      "signature.view_metadata",
      "signature.view_audit",
      "documents.view",
      "reports.dashboard.view",
      "reports.sales.view",
      "reports.documents.view",
      "audit.view",
      "platform.assisted_commerce.moderate"
    ],
    "systemRole": true,
    "critical": true,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_organization_owner",
    "code": "organization_owner",
    "organizationId": null,
    "scope": "organization",
    "type": "organization",
    "name": "Organization Owner",
    "description": "Dueño del negocio. Control total operativo y administrativo de su organización.",
    "permissionKeys": [
      "credentials.users.view",
      "credentials.users.create",
      "credentials.users.invite",
      "credentials.users.reset_password",
      "credentials.users.block",
      "credentials.users.unblock",
      "credentials.sessions.revoke",
      "credentials.roles.view",
      "credentials.roles.assign",
      "credentials.roles.manage",
      "organization.view",
      "organization.update",
      "organization.update_profile",
      "organization.members.view",
      "organization.members.manage",
      "branches.view",
      "branches.create",
      "branches.update",
      "settings.branches.view",
      "settings.branches.manage",
      "settings.emission_points.view",
      "settings.emission_points.manage",
      "activities.view",
      "activities.create",
      "activities.update",
      "catalog.view",
      "catalog.local.view",
      "catalog.local.copy_from_master",
      "catalog.local.update_local_copy",
      "catalog.local.change_price",
      "catalog.local.change_tax_profile",
      "catalog.local.disable_local_copy",
      "catalog.local.request_new_item",
      "catalog.identifiers.scan",
      "catalog.identifiers.add_local",
      "catalog.units.manage_conversions",
      "customers.view",
      "customers.create",
      "customers.update",
      "sales.view",
      "sales.create",
      "sales.confirm",
      "sales.cancel",
      "sales.cancel_after_payment",
      "sales.close",
      "sales.apply_discount",
      "sales.items.change_status",
      "payments.view",
      "payments.collect",
      "payments.partial_collect",
      "payments.mark_as_credit",
      "payments.refund",
      "payments.reverse",
      "receivables.view",
      "receivables.create",
      "receivables.register_payment",
      "cash.view",
      "cash.open",
      "cash.close",
      "cash.session.view_current",
      "cash.session.view_history",
      "cash.session.open",
      "cash.session.close",
      "cash.movements.register_inflow",
      "cash.movements.register_outflow",
      "cash.movements.adjust",
      "inventory.view",
      "inventory.adjust",
      "documents.view",
      "documents.generate_internal_ticket",
      "documents.generate_physical_sale_note_registry",
      "documents.issue_electronic_invoice",
      "documents.download_pdf",
      "documents.download_xml",
      "documents.invoice.issue",
      "documents.invoice.download_xml",
      "documents.invoice.download_ride",
      "documents.invoice.request_cancellation",
      "tax.manage",
      "tax.settings.view",
      "tax.settings.update_organization_regime",
      "tax.profiles.assign_to_item",
      "signature.view_metadata",
      "signature.upload",
      "signature.replace",
      "signature.revoke",
      "signature.test",
      "signature.use_for_invoicing",
      "signature.view_audit",
      "reports.dashboard.view",
      "reports.sales.view",
      "reports.cash.view",
      "reports.tax.view",
      "reports.documents.view",
      "audit.view",
      "catalog.price.view",
      "catalog.price.update",
      "catalog.price_history.view",
      "catalog.search_metadata.view",
      "catalog.search_metadata.update",
      "catalog.public_visibility.view",
      "catalog.public_visibility.update",
      "catalog.public_visibility.hide",
      "catalog.public_visibility.republish",
      "catalog.public_display.update_price_mode",
      "catalog.public_display.update_stock_mode",
      "catalog.public_display.allow_comparison",
      "catalog.public_preview.view",
      "branch.location.view",
      "branch.location.update",
      "branch.location.public_visibility.view",
      "branch.location.public_visibility.update",
      "branch.location.privacy_mode.update",
      "discovery.settings.view",
      "discovery.settings.update",
      "discovery.preview.view",
      "discovery.audit.view",
      "business_hours.view",
      "business_hours.update",
      "business_hours.public_visibility.update"
    ],
    "systemRole": true,
    "critical": true,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_organization_admin",
    "code": "organization_admin",
    "organizationId": null,
    "scope": "organization",
    "type": "organization",
    "name": "Organization Admin",
    "description": "Administra usuarios, roles, configuración, catálogo, firma y operación del negocio.",
    "permissionKeys": [
      "credentials.users.view",
      "credentials.users.create",
      "credentials.users.invite",
      "credentials.users.reset_password",
      "credentials.users.block",
      "credentials.users.unblock",
      "credentials.sessions.revoke",
      "credentials.roles.view",
      "credentials.roles.assign",
      "credentials.roles.manage",
      "organization.view",
      "organization.update",
      "organization.update_profile",
      "organization.members.view",
      "organization.members.manage",
      "branches.view",
      "branches.create",
      "branches.update",
      "settings.branches.view",
      "settings.branches.manage",
      "settings.emission_points.view",
      "settings.emission_points.manage",
      "activities.view",
      "activities.create",
      "activities.update",
      "catalog.view",
      "catalog.local.view",
      "catalog.local.copy_from_master",
      "catalog.local.update_local_copy",
      "catalog.local.change_price",
      "catalog.local.change_tax_profile",
      "catalog.local.disable_local_copy",
      "catalog.local.request_new_item",
      "catalog.identifiers.scan",
      "catalog.identifiers.add_local",
      "catalog.units.manage_conversions",
      "customers.view",
      "customers.create",
      "customers.update",
      "sales.view",
      "sales.create",
      "sales.confirm",
      "sales.cancel",
      "sales.cancel_after_payment",
      "sales.close",
      "sales.apply_discount",
      "sales.items.change_status",
      "payments.view",
      "payments.collect",
      "payments.partial_collect",
      "payments.mark_as_credit",
      "payments.refund",
      "receivables.view",
      "receivables.create",
      "receivables.register_payment",
      "cash.view",
      "cash.open",
      "cash.close",
      "cash.session.view_current",
      "cash.session.view_history",
      "cash.session.open",
      "cash.session.close",
      "cash.movements.register_inflow",
      "cash.movements.register_outflow",
      "inventory.view",
      "inventory.adjust",
      "documents.view",
      "documents.generate_internal_ticket",
      "documents.generate_physical_sale_note_registry",
      "documents.issue_electronic_invoice",
      "documents.download_pdf",
      "documents.download_xml",
      "documents.invoice.issue",
      "documents.invoice.download_xml",
      "documents.invoice.download_ride",
      "documents.invoice.request_cancellation",
      "tax.manage",
      "tax.settings.view",
      "tax.settings.update_organization_regime",
      "tax.profiles.assign_to_item",
      "signature.view_metadata",
      "signature.upload",
      "signature.replace",
      "signature.test",
      "signature.use_for_invoicing",
      "signature.view_audit",
      "reports.dashboard.view",
      "reports.sales.view",
      "reports.cash.view",
      "reports.tax.view",
      "reports.documents.view",
      "audit.view",
      "catalog.price.view",
      "catalog.price.update",
      "catalog.price_history.view",
      "catalog.search_metadata.view",
      "catalog.search_metadata.update",
      "catalog.public_visibility.view",
      "catalog.public_visibility.update",
      "catalog.public_visibility.hide",
      "catalog.public_visibility.republish",
      "catalog.public_display.update_price_mode",
      "catalog.public_display.update_stock_mode",
      "catalog.public_preview.view",
      "branch.location.view",
      "branch.location.update",
      "branch.location.public_visibility.view",
      "branch.location.public_visibility.update",
      "branch.location.privacy_mode.update",
      "discovery.settings.view",
      "discovery.settings.update",
      "discovery.preview.view",
      "discovery.audit.view",
      "business_hours.view",
      "business_hours.update",
      "business_hours.public_visibility.update"
    ],
    "systemRole": true,
    "critical": true,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_manager",
    "code": "manager",
    "organizationId": null,
    "scope": "organization",
    "type": "organization",
    "name": "Manager",
    "description": "Encargado operativo. Puede vender, cobrar, cerrar caja y gestionar operación diaria.",
    "permissionKeys": [
      "organization.view",
      "organization.members.view",
      "activities.view",
      "branches.view",
      "settings.branches.view",
      "catalog.view",
      "catalog.local.view",
      "catalog.local.copy_from_master",
      "catalog.local.update_local_copy",
      "catalog.local.change_price",
      "catalog.local.disable_local_copy",
      "catalog.local.request_new_item",
      "catalog.identifiers.scan",
      "catalog.identifiers.add_local",
      "customers.view",
      "customers.create",
      "customers.update",
      "sales.view",
      "sales.create",
      "sales.confirm",
      "sales.cancel",
      "sales.close",
      "sales.apply_discount",
      "sales.items.change_status",
      "payments.view",
      "payments.collect",
      "payments.partial_collect",
      "payments.mark_as_credit",
      "receivables.view",
      "receivables.create",
      "receivables.register_payment",
      "cash.view",
      "cash.session.view_current",
      "cash.session.view_history",
      "cash.session.open",
      "cash.session.close",
      "cash.movements.register_inflow",
      "cash.movements.register_outflow",
      "inventory.view",
      "inventory.adjust",
      "documents.view",
      "documents.generate_internal_ticket",
      "documents.generate_physical_sale_note_registry",
      "documents.issue_electronic_invoice",
      "signature.view_metadata",
      "signature.use_for_invoicing",
      "reports.dashboard.view",
      "reports.sales.view",
      "reports.cash.view",
      "reports.documents.view"
    ],
    "systemRole": true,
    "critical": false,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_operator",
    "code": "operator",
    "organizationId": null,
    "scope": "organization",
    "type": "organization",
    "name": "Operator",
    "description": "Operador básico para atención, ventas, pedidos, cobros permitidos y tickets internos.",
    "permissionKeys": [
      "organization.view",
      "activities.view",
      "catalog.view",
      "catalog.local.view",
      "catalog.identifiers.scan",
      "customers.view",
      "customers.create",
      "sales.view",
      "sales.create",
      "sales.confirm",
      "sales.items.change_status",
      "payments.collect",
      "payments.partial_collect",
      "cash.session.view_current",
      "documents.generate_internal_ticket"
    ],
    "systemRole": true,
    "critical": false,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_accountant",
    "code": "accountant",
    "organizationId": null,
    "scope": "organization",
    "type": "organization",
    "name": "Accountant",
    "description": "Consulta ventas, caja, documentos, impuestos, auditoría y descarga XML/RIDE/PDF.",
    "permissionKeys": [
      "organization.view",
      "organization.members.view",
      "branches.view",
      "settings.emission_points.view",
      "customers.view",
      "sales.view",
      "payments.view",
      "receivables.view",
      "cash.view",
      "cash.session.view_current",
      "cash.session.view_history",
      "documents.view",
      "documents.download_pdf",
      "documents.download_xml",
      "documents.invoice.download_xml",
      "documents.invoice.download_ride",
      "tax.settings.view",
      "signature.view_metadata",
      "signature.view_audit",
      "reports.dashboard.view",
      "reports.sales.view",
      "reports.cash.view",
      "reports.tax.view",
      "reports.documents.view",
      "audit.view"
    ],
    "systemRole": true,
    "critical": false,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  },
  {
    "_id": "role_read_only",
    "code": "read_only",
    "organizationId": null,
    "scope": "organization",
    "type": "organization",
    "name": "Read Only",
    "description": "Lectura general sin modificación de datos operativos ni configuración crítica.",
    "permissionKeys": [
      "organization.view",
      "organization.members.view",
      "activities.view",
      "branches.view",
      "settings.branches.view",
      "settings.emission_points.view",
      "catalog.view",
      "catalog.local.view",
      "customers.view",
      "sales.view",
      "payments.view",
      "receivables.view",
      "cash.view",
      "cash.session.view_current",
      "cash.session.view_history",
      "inventory.view",
      "documents.view",
      "signature.view_metadata",
      "reports.dashboard.view",
      "reports.sales.view",
      "reports.cash.view",
      "reports.documents.view"
    ],
    "systemRole": true,
    "critical": false,
    "editable": false,
    "status": "active",
    "schemaVersion": 1
  }
];

db.roles.createIndex(
  { code: 1 },
  { unique: true, name: "uq_roles_code" }
);

db.roles.createIndex(
  { scope: 1, status: 1 },
  { name: "idx_roles_scope_status" }
);

db.roles.createIndex(
  { organizationId: 1, code: 1 },
  { name: "idx_roles_organization_code" }
);

roles.forEach((role) => {
  db.roles.updateOne(
    { code: role.code },
    {
      $set: {
        ...role,
        updatedAt: now,
        updatedBy: "system",
      },
      $setOnInsert: {
        createdAt: now,
        createdBy: "system",
        version: 1,
      },
    },
    { upsert: true },
  );
});

roles.forEach((role) => {
  db.audit_logs.insertOne({
    _id: `audit_role_seed_${role.code}_${now.getTime()}`,
    eventType: "ROLE_CREATED",
    actorType: "system",
    actorId: "system",
    organizationId: role.organizationId,
    entityType: "role",
    entityId: role._id,
    entityCode: role.code,
    metadata: {
      seed: "005_11_seed_system_roles",
      permissionsCount: role.permissionKeys.length,
      roleScope: role.scope,
      roleType: role.type,
    },
    occurredAt: now,
    schemaVersion: 1,
  });
});
