package com.hermes.application.electronicinvoicing

import com.hermes.domain.electronicinvoicing.SriAccessKey
import com.hermes.domain.electronicinvoicing.SriDocumentType
import com.hermes.domain.electronicinvoicing.SriEmissionType
import com.hermes.domain.electronicinvoicing.SriEnvironment
import com.hermes.domain.electronicinvoicing.SriIdentificationType
import com.hermes.domain.electronicinvoicing.SriInvoicePaymentForm
import com.hermes.domain.electronicinvoicing.SriInvoiceRimpeLegend
import com.hermes.domain.electronicinvoicing.SriInvoiceSchemaVersion
import com.hermes.domain.electronicinvoicing.SriSequential
import com.hermes.domain.electronicinvoicing.SriSeries
import com.hermes.domain.shared.DomainRuleViolation
import java.math.BigDecimal
import java.time.LocalDate

@Suppress("LongParameterList")
data class BuildSriInvoiceXmlCommand(
    val schemaVersion: SriInvoiceSchemaVersion = SriInvoiceSchemaVersion.V2_1_0,
    val infoTributaria: SriInvoiceTaxInfo,
    val infoFactura: SriInvoiceInfo,
    val detalles: List<SriInvoiceDetail>,
    val infoAdicional: List<SriInvoiceAdditionalField> = emptyList(),
) {
    init {
        infoTributaria.documentType.assertMvpSupported()
        if (infoTributaria.documentType != SriDocumentType.INVOICE) {
            throw DomainRuleViolation("Only SRI invoice XML can be generated by this builder.")
        }
        if (detalles.isEmpty()) throw DomainRuleViolation("SRI invoice XML requires at least one detail.")
        if (infoAdicional.size > MAX_ADDITIONAL_FIELDS) {
            throw DomainRuleViolation("SRI invoice XML supports at most $MAX_ADDITIONAL_FIELDS additional fields.")
        }
        if (infoTributaria.accessKey.documentType != infoTributaria.documentType) {
            throw DomainRuleViolation("Access key document type does not match invoice document type.")
        }
        if (infoTributaria.accessKey.environment != infoTributaria.environment) {
            throw DomainRuleViolation("Access key environment does not match invoice environment.")
        }
        if (infoTributaria.accessKey.series != infoTributaria.series) {
            throw DomainRuleViolation("Access key series does not match invoice series.")
        }
        if (infoTributaria.accessKey.sequential != infoTributaria.sequential) {
            throw DomainRuleViolation("Access key sequential does not match invoice sequential.")
        }
        infoFactura.buyerIdentificationType.assertValidFor(
            identification = infoFactura.buyerIdentification,
            documentType = infoTributaria.documentType,
        )
        assertTotalsMatchDetails()
    }

    private fun assertTotalsMatchDetails() {
        val detailsSubtotal = detalles.sumOf { it.precioTotalSinImpuesto }.moneyScale()
        val detailsDiscount = detalles.sumOf { it.descuento }.moneyScale()
        val detailsTaxTotal = detalles.flatMap { it.impuestos }.sumOf { it.valor }.moneyScale()
        val expectedImporteTotal = (detailsSubtotal + detailsTaxTotal + infoFactura.propina).moneyScale()

        if (detailsSubtotal != infoFactura.totalSinImpuestos) {
            throw DomainRuleViolation("SRI invoice totalSinImpuestos must match detail subtotals.")
        }
        if (detailsDiscount != infoFactura.totalDescuento) {
            throw DomainRuleViolation("SRI invoice totalDescuento must match detail discounts.")
        }
        if (detailsTaxTotal != infoFactura.totalConImpuestos.sumOf { it.valor }.moneyScale()) {
            throw DomainRuleViolation("SRI invoice total tax summary must match detail taxes.")
        }
        if (expectedImporteTotal != infoFactura.importeTotal) {
            throw DomainRuleViolation("SRI invoice importeTotal must match subtotal + tax + propina.")
        }
        val paymentTotal = infoFactura.pagos.sumOf { it.total }.moneyScale()
        if (paymentTotal != infoFactura.importeTotal) {
            throw DomainRuleViolation("SRI invoice payment total must match importeTotal.")
        }
    }

    companion object {
        const val MAX_ADDITIONAL_FIELDS = 15
    }
}

@Suppress("LongParameterList")
data class SriInvoiceTaxInfo(
    val environment: SriEnvironment,
    val emissionType: SriEmissionType = SriEmissionType.NORMAL,
    val razonSocial: String,
    val nombreComercial: String? = null,
    val ruc: String,
    val accessKey: SriAccessKey,
    val documentType: SriDocumentType = SriDocumentType.INVOICE,
    val series: SriSeries,
    val sequential: SriSequential,
    val dirMatriz: String,
    val agenteRetencion: String? = null,
    val contribuyenteRimpe: SriInvoiceRimpeLegend = SriInvoiceRimpeLegend.NONE,
) {
    init {
        if (razonSocial.trim().isBlank()) throw DomainRuleViolation("Issuer razonSocial cannot be blank.")
        if (!ruc.trim().matches(Regex("\\d{13}"))) throw DomainRuleViolation("Issuer RUC must contain exactly 13 digits.")
        if (dirMatriz.trim().isBlank()) throw DomainRuleViolation("Issuer dirMatriz cannot be blank.")
        if (accessKey.ruc != ruc.trim()) throw DomainRuleViolation("Access key RUC does not match issuer RUC.")
        if (agenteRetencion != null && !agenteRetencion.matches(Regex("\\d+"))) {
            throw DomainRuleViolation("agenteRetencion must contain digits only when present.")
        }
    }
}

@Suppress("LongParameterList")
data class SriInvoiceInfo(
    val fechaEmision: LocalDate,
    val dirEstablecimiento: String? = null,
    val contribuyenteEspecial: String? = null,
    val obligadoContabilidad: SriAccountingObligation? = null,
    val buyerIdentificationType: SriIdentificationType,
    val buyerLegalName: String,
    val buyerIdentification: String,
    val buyerAddress: String? = null,
    val totalSinImpuestos: BigDecimal,
    val totalDescuento: BigDecimal,
    val totalConImpuestos: List<SriInvoiceTotalTax>,
    val propina: BigDecimal = BigDecimal.ZERO.moneyScale(),
    val importeTotal: BigDecimal,
    val moneda: String = "DOLAR",
    val pagos: List<SriInvoicePayment>,
) {
    init {
        if (buyerLegalName.trim().isBlank()) throw DomainRuleViolation("Buyer legal name cannot be blank.")
        if (moneda.trim().isBlank()) throw DomainRuleViolation("SRI invoice currency label cannot be blank.")
        if (totalConImpuestos.isEmpty()) throw DomainRuleViolation("SRI invoice requires at least one total tax line.")
        if (pagos.isEmpty()) throw DomainRuleViolation("SRI invoice requires at least one payment.")
        listOf(totalSinImpuestos, totalDescuento, propina, importeTotal).forEach { value ->
            if (value.signum() < 0) throw DomainRuleViolation("SRI invoice monetary values cannot be negative.")
            if (value.scale() > 2) throw DomainRuleViolation("SRI invoice monetary values require at most 2 decimals.")
        }
    }
}

enum class SriAccountingObligation(val xmlValue: String) {
    YES("SI"),
    NO("NO"),
}

data class SriInvoiceTotalTax(
    val codigo: String,
    val codigoPorcentaje: String,
    val baseImponible: BigDecimal,
    val tarifa: BigDecimal,
    val valor: BigDecimal,
    val descuentoAdicional: BigDecimal? = null,
) {
    init {
        requireDigits(codigo, "Tax code")
        requireDigits(codigoPorcentaje, "Tax rate code")
        listOf(baseImponible, tarifa, valor).forEach { value ->
            if (value.signum() < 0) throw DomainRuleViolation("SRI invoice tax values cannot be negative.")
        }
        if (baseImponible.scale() > 2 || valor.scale() > 2) {
            throw DomainRuleViolation("SRI invoice tax money values require at most 2 decimals.")
        }
        if (tarifa.scale() > 2) throw DomainRuleViolation("SRI invoice tax rate requires at most 2 decimals.")
    }
}

data class SriInvoicePayment(
    val formaPago: SriInvoicePaymentForm,
    val total: BigDecimal,
    val plazo: BigDecimal? = null,
    val unidadTiempo: String? = null,
) {
    init {
        if (total.signum() < 0) throw DomainRuleViolation("SRI invoice payment total cannot be negative.")
        if (total.scale() > 2) throw DomainRuleViolation("SRI invoice payment total requires at most 2 decimals.")
        if (plazo != null && plazo.signum() < 0) throw DomainRuleViolation("SRI invoice payment term cannot be negative.")
        if (unidadTiempo != null && unidadTiempo.trim().isBlank()) {
            throw DomainRuleViolation("SRI invoice payment unidadTiempo cannot be blank when present.")
        }
    }
}

@Suppress("LongParameterList")
data class SriInvoiceDetail(
    val codigoPrincipal: String,
    val codigoAuxiliar: String? = null,
    val descripcion: String,
    val unidadMedida: String? = null,
    val cantidad: BigDecimal,
    val precioUnitario: BigDecimal,
    val descuento: BigDecimal,
    val precioTotalSinImpuesto: BigDecimal,
    val detallesAdicionales: List<SriInvoiceDetailAdditional> = emptyList(),
    val impuestos: List<SriInvoiceDetailTax>,
) {
    init {
        if (codigoPrincipal.trim().isBlank()) throw DomainRuleViolation("Invoice detail codigoPrincipal cannot be blank.")
        if (descripcion.trim().isBlank()) throw DomainRuleViolation("Invoice detail descripcion cannot be blank.")
        if (cantidad.signum() <= 0) throw DomainRuleViolation("Invoice detail quantity must be greater than zero.")
        if (precioUnitario.signum() < 0 || descuento.signum() < 0 || precioTotalSinImpuesto.signum() < 0) {
            throw DomainRuleViolation("Invoice detail money values cannot be negative.")
        }
        if (cantidad.scale() > 6) throw DomainRuleViolation("Invoice detail quantity requires at most 6 decimals.")
        if (precioUnitario.scale() > 6) throw DomainRuleViolation("Invoice detail unit price requires at most 6 decimals.")
        if (descuento.scale() > 2 || precioTotalSinImpuesto.scale() > 2) {
            throw DomainRuleViolation("Invoice detail totals require at most 2 decimals.")
        }
        if (impuestos.isEmpty()) throw DomainRuleViolation("Invoice detail requires at least one tax line.")
        if (detallesAdicionales.size > 3) throw DomainRuleViolation("Invoice detail supports at most 3 additional detail fields.")
    }
}

data class SriInvoiceDetailAdditional(
    val nombre: String,
    val valor: String,
) {
    init {
        if (nombre.trim().isBlank()) throw DomainRuleViolation("Invoice detail additional name cannot be blank.")
        if (valor.trim().isBlank()) throw DomainRuleViolation("Invoice detail additional value cannot be blank.")
    }
}

data class SriInvoiceDetailTax(
    val codigo: String,
    val codigoPorcentaje: String,
    val tarifa: BigDecimal,
    val baseImponible: BigDecimal,
    val valor: BigDecimal,
) {
    init {
        requireDigits(codigo, "Detail tax code")
        requireDigits(codigoPorcentaje, "Detail tax rate code")
        if (tarifa.signum() < 0 || baseImponible.signum() < 0 || valor.signum() < 0) {
            throw DomainRuleViolation("Invoice detail tax values cannot be negative.")
        }
        if (tarifa.scale() > 2) throw DomainRuleViolation("Invoice detail tax rate requires at most 2 decimals.")
        if (baseImponible.scale() > 2 || valor.scale() > 2) {
            throw DomainRuleViolation("Invoice detail tax money values require at most 2 decimals.")
        }
    }
}

data class SriInvoiceAdditionalField(
    val nombre: String,
    val valor: String,
) {
    init {
        if (nombre.trim().isBlank()) throw DomainRuleViolation("SRI invoice additional field name cannot be blank.")
        if (valor.trim().isBlank()) throw DomainRuleViolation("SRI invoice additional field value cannot be blank.")
        if (nombre.length > 300 || valor.length > 300) {
            throw DomainRuleViolation("SRI invoice additional fields support at most 300 characters.")
        }
    }
}

internal fun BigDecimal.moneyScale(): BigDecimal = setScale(2)

private fun requireDigits(value: String, label: String) {
    if (!value.trim().matches(Regex("\\d+"))) throw DomainRuleViolation("$label must contain digits only.")
}
