[versions]
koin = "4.2.0"
kotlin = "2.3.21"
logback = "1.5.21"
mongodb = "5.7"

[libraries]
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-loggerSlf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mongodb-bom = { module = "org.mongodb:mongodb-driver-bom", version.ref = "mongodb" }
mongodb-driverSync = { module = "org.mongodb:mongodb-driver-sync" }
mongodb-driverKotlinCoroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
