package com.hermes.infrastructure.mongo

object MongoCollectionNames {
    const val SCHEMA_MIGRATIONS = "schema_migrations"
    const val SCHEMA_MIGRATION_LOCKS = "schema_migration_locks"
    const val DATABASE_HEALTH_CHECKS = "database_health_checks"

    const val ORGANIZATIONS = "organizations"
    const val ORGANIZATION_ACTIVITIES = "organization_activities"
    const val BRANCHES = "branches"
    const val EMISSION_POINTS = "emission_points"
    const val USERS = "users"
    const val MEMBERSHIPS = "memberships"
    const val ROLES = "roles"
    const val PERMISSIONS = "permissions"
    const val CREDENTIAL_EVENTS = "credential_events"
    const val USER_SESSIONS = "user_sessions"
    const val PLATFORM_CATALOG_FAMILIES = "platform_catalog_families"
    const val PLATFORM_CATALOG_TEMPLATES = "platform_catalog_templates"
    const val ORGANIZATION_CATALOG_ITEMS = "organization_catalog_items"
    const val CATALOG_ITEM_REQUESTS = "catalog_item_requests"
    const val TAX_RATES = "tax_rates"
    const val TAX_PROFILES = "tax_profiles"
    const val ORGANIZATION_TAX_SETTINGS = "organization_tax_settings"
    const val CUSTOMERS = "customers"
    const val SALES = "sales"
    const val RESERVATIONS = "reservations"
    const val PAYMENTS = "payments"
    const val RECEIVABLES = "receivables"
    const val CASH_SESSIONS = "cash_sessions"
    const val CASH_MOVEMENTS = "cash_movements"
    const val COMMERCIAL_DOCUMENTS = "commercial_documents"
    const val ELECTRONIC_DOCUMENT_PAYLOADS = "electronic_document_payloads"
    const val SRI_SUBMISSIONS = "sri_submissions"
    const val ELECTRONIC_SIGNATURES = "electronic_signatures"
    const val STOCK_BALANCES = "stock_balances"
    const val STOCK_MOVEMENTS = "stock_movements"
    const val AUDIT_LOGS = "audit_logs"
    const val DOMAIN_EVENTS = "domain_events"
    const val OUTBOX_EVENTS = "outbox_events"
    const val COUNTERS = "counters"
}
