package com.hermes.domain.role

import com.hermes.domain.permission.PermissionCatalog


object RoleSeed {
    val all: List<RoleDefinition> = listOf(
        platformSuperAdmin(),
        platformSupport(),
        organizationOwner(),
        organizationAdmin(),
        manager(),
        operator(),
        accountant(),
        readOnly(),
    )

    val byCode: Map<String, RoleDefinition> = all.associateBy { it.code }

    fun get(code: SystemRoleCode): RoleDefinition = byCode.getValue(code.code)

    fun get(code: String): RoleDefinition = byCode.getValue(code)

    fun organizationRoles(): List<RoleDefinition> = all.filter { it.scope == RoleScope.ORGANIZATION }

    fun platformRoles(): List<RoleDefinition> = all.filter { it.scope == RoleScope.PLATFORM }

    fun requiredPermissionCodes(): Set<String> = RoleSeedRules.requiredPermissions(all)

    private fun platformSuperAdmin(): RoleDefinition = role(
        code = SystemRoleCode.PLATFORM_SUPER_ADMIN.code,
        scope = RoleScope.PLATFORM,
        type = RoleType.SYSTEM,
        name = "Platform Super Admin",
        description = "Control total de plataforma. Uso extremadamente restringido.",
        permissionKeys = setOf(PermissionCatalog.ALL),
        critical = true,
        editable = false,
    )

    private fun platformSupport(): RoleDefinition = role(
        code = SystemRoleCode.PLATFORM_SUPPORT.code,
        scope = RoleScope.PLATFORM,
        type = RoleType.SYSTEM,
        name = "Platform Support",
        description = "Soporte operativo de plataforma sin control total destructivo.",
        permissionKeys = setOf(
            PermissionCatalog.ORGANIZATION_VIEW,
            PermissionCatalog.ORGANIZATION_MEMBERS_VIEW,
            PermissionCatalog.CREDENTIALS_USERS_VIEW,
            PermissionCatalog.CREDENTIALS_SESSIONS_REVOKE,
            PermissionCatalog.CREDENTIALS_ROLES_VIEW,
            PermissionCatalog.BRANCHES_VIEW,
            PermissionCatalog.SETTINGS_BRANCHES_VIEW,
            PermissionCatalog.SETTINGS_EMISSION_POINTS_VIEW,
            PermissionCatalog.CATALOG_VIEW,
            PermissionCatalog.CATALOG_LOCAL_VIEW,
            PermissionCatalog.CATALOG_IDENTIFIERS_VERIFY_MASTER,
            PermissionCatalog.CATALOG_IDENTIFIERS_RESOLVE_CONFLICT,
            PermissionCatalog.SIGNATURE_VIEW_METADATA,
            PermissionCatalog.SIGNATURE_VIEW_AUDIT,
            PermissionCatalog.DOCUMENTS_VIEW,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_LIST,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW_ERRORS,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW_AUDIT,
            PermissionCatalog.REPORTS_DASHBOARD_VIEW,
            PermissionCatalog.REPORTS_SALES_VIEW,
            PermissionCatalog.REPORTS_DOCUMENTS_VIEW,
            PermissionCatalog.AUDIT_VIEW,
            PermissionCatalog.PLATFORM_ASSISTED_COMMERCE_MODERATE,
        ),
        critical = true,
        editable = false,
    )

    private fun organizationOwner(): RoleDefinition = role(
        code = SystemRoleCode.ORGANIZATION_OWNER.code,
        scope = RoleScope.ORGANIZATION,
        type = RoleType.ORGANIZATION,
        name = "Organization Owner",
        description = "Dueño del negocio. Control total operativo y administrativo de su organización.",
        permissionKeys = organizationOwnerPermissions(),
        critical = true,
        editable = false,
    )

    private fun organizationAdmin(): RoleDefinition = role(
        code = SystemRoleCode.ORGANIZATION_ADMIN.code,
        scope = RoleScope.ORGANIZATION,
        type = RoleType.ORGANIZATION,
        name = "Organization Admin",
        description = "Administra usuarios, roles, configuración, catálogo, firma y operación del negocio.",
        permissionKeys = organizationAdminPermissions(),
        critical = true,
        editable = false,
    )

    private fun manager(): RoleDefinition = role(
        code = SystemRoleCode.MANAGER.code,
        scope = RoleScope.ORGANIZATION,
        type = RoleType.ORGANIZATION,
        name = "Manager",
        description = "Encargado operativo. Puede vender, cobrar, cerrar caja y gestionar operación diaria.",
        permissionKeys = setOf(
            PermissionCatalog.ORGANIZATION_VIEW,
            PermissionCatalog.ORGANIZATION_MEMBERS_VIEW,
            PermissionCatalog.ACTIVITIES_VIEW,
            PermissionCatalog.BRANCHES_VIEW,
            PermissionCatalog.SETTINGS_BRANCHES_VIEW,
            PermissionCatalog.CATALOG_VIEW,
            PermissionCatalog.CATALOG_LOCAL_VIEW,
            PermissionCatalog.CATALOG_LOCAL_COPY_FROM_MASTER,
            PermissionCatalog.CATALOG_LOCAL_UPDATE_LOCAL_COPY,
            PermissionCatalog.CATALOG_LOCAL_CHANGE_PRICE,
            PermissionCatalog.CATALOG_LOCAL_DISABLE_LOCAL_COPY,
            PermissionCatalog.CATALOG_LOCAL_REQUEST_NEW_ITEM,
            PermissionCatalog.CATALOG_IDENTIFIERS_SCAN,
            PermissionCatalog.CATALOG_IDENTIFIERS_ADD_LOCAL,
            PermissionCatalog.CUSTOMERS_VIEW,
            PermissionCatalog.CUSTOMERS_CREATE,
            PermissionCatalog.CUSTOMERS_UPDATE,
            PermissionCatalog.SALES_VIEW,
            PermissionCatalog.SALES_CREATE,
            PermissionCatalog.SALES_CONFIRM,
            PermissionCatalog.SALES_CANCEL,
            PermissionCatalog.SALES_CLOSE,
            PermissionCatalog.SALES_APPLY_DISCOUNT,
            PermissionCatalog.SALES_ITEMS_CHANGE_STATUS,
            PermissionCatalog.PAYMENTS_VIEW,
            PermissionCatalog.PAYMENTS_COLLECT,
            PermissionCatalog.PAYMENTS_PARTIAL_COLLECT,
            PermissionCatalog.PAYMENTS_MARK_AS_CREDIT,
            PermissionCatalog.RECEIVABLES_VIEW,
            PermissionCatalog.RECEIVABLES_CREATE,
            PermissionCatalog.RECEIVABLES_REGISTER_PAYMENT,
            PermissionCatalog.CASH_VIEW,
            PermissionCatalog.CASH_SESSION_VIEW_CURRENT,
            PermissionCatalog.CASH_SESSION_VIEW_HISTORY,
            PermissionCatalog.CASH_SESSION_OPEN,
            PermissionCatalog.CASH_SESSION_CLOSE,
            PermissionCatalog.CASH_MOVEMENTS_REGISTER_INFLOW,
            PermissionCatalog.CASH_MOVEMENTS_REGISTER_OUTFLOW,
            PermissionCatalog.INVENTORY_VIEW,
            PermissionCatalog.INVENTORY_ADJUST,
            PermissionCatalog.DOCUMENTS_VIEW,
            PermissionCatalog.DOCUMENTS_GENERATE_INTERNAL_TICKET,
            PermissionCatalog.DOCUMENTS_GENERATE_PHYSICAL_SALE_NOTE_REGISTRY,
            PermissionCatalog.DOCUMENTS_ISSUE_ELECTRONIC_INVOICE,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_LIST,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_ISSUE,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_EMAIL,
            PermissionCatalog.SIGNATURE_VIEW_METADATA,
            PermissionCatalog.SIGNATURE_USE_FOR_INVOICING,
            PermissionCatalog.REPORTS_DASHBOARD_VIEW,
            PermissionCatalog.REPORTS_SALES_VIEW,
            PermissionCatalog.REPORTS_CASH_VIEW,
            PermissionCatalog.REPORTS_DOCUMENTS_VIEW,
        ),
        critical = false,
        editable = false,
    )

    private fun operator(): RoleDefinition = role(
        code = SystemRoleCode.OPERATOR.code,
        scope = RoleScope.ORGANIZATION,
        type = RoleType.ORGANIZATION,
        name = "Operator",
        description = "Operador básico para atención, ventas, pedidos, cobros permitidos y tickets internos.",
        permissionKeys = setOf(
            PermissionCatalog.ORGANIZATION_VIEW,
            PermissionCatalog.ACTIVITIES_VIEW,
            PermissionCatalog.CATALOG_VIEW,
            PermissionCatalog.CATALOG_LOCAL_VIEW,
            PermissionCatalog.CATALOG_IDENTIFIERS_SCAN,
            PermissionCatalog.CUSTOMERS_VIEW,
            PermissionCatalog.CUSTOMERS_CREATE,
            PermissionCatalog.SALES_VIEW,
            PermissionCatalog.SALES_CREATE,
            PermissionCatalog.SALES_CONFIRM,
            PermissionCatalog.SALES_ITEMS_CHANGE_STATUS,
            PermissionCatalog.PAYMENTS_COLLECT,
            PermissionCatalog.PAYMENTS_PARTIAL_COLLECT,
            PermissionCatalog.CASH_SESSION_VIEW_CURRENT,
            PermissionCatalog.DOCUMENTS_GENERATE_INTERNAL_TICKET,
        ),
        critical = false,
        editable = false,
    )

    private fun accountant(): RoleDefinition = role(
        code = SystemRoleCode.ACCOUNTANT.code,
        scope = RoleScope.ORGANIZATION,
        type = RoleType.ORGANIZATION,
        name = "Accountant",
        description = "Consulta ventas, caja, documentos, impuestos, auditoría y descarga XML/RIDE/PDF.",
        permissionKeys = setOf(
            PermissionCatalog.ORGANIZATION_VIEW,
            PermissionCatalog.ORGANIZATION_MEMBERS_VIEW,
            PermissionCatalog.BRANCHES_VIEW,
            PermissionCatalog.SETTINGS_EMISSION_POINTS_VIEW,
            PermissionCatalog.CUSTOMERS_VIEW,
            PermissionCatalog.SALES_VIEW,
            PermissionCatalog.PAYMENTS_VIEW,
            PermissionCatalog.RECEIVABLES_VIEW,
            PermissionCatalog.CASH_VIEW,
            PermissionCatalog.CASH_SESSION_VIEW_CURRENT,
            PermissionCatalog.CASH_SESSION_VIEW_HISTORY,
            PermissionCatalog.DOCUMENTS_VIEW,
            PermissionCatalog.DOCUMENTS_DOWNLOAD_PDF,
            PermissionCatalog.DOCUMENTS_DOWNLOAD_XML,
            PermissionCatalog.DOCUMENTS_INVOICE_DOWNLOAD_XML,
            PermissionCatalog.DOCUMENTS_INVOICE_DOWNLOAD_RIDE,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_LIST,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_DOWNLOAD_XML,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_DOWNLOAD_RIDE,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW_ERRORS,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW_AUDIT,
            PermissionCatalog.TAX_SETTINGS_VIEW,
            PermissionCatalog.SIGNATURE_VIEW_METADATA,
            PermissionCatalog.SIGNATURE_VIEW_AUDIT,
            PermissionCatalog.REPORTS_DASHBOARD_VIEW,
            PermissionCatalog.REPORTS_SALES_VIEW,
            PermissionCatalog.REPORTS_CASH_VIEW,
            PermissionCatalog.REPORTS_TAX_VIEW,
            PermissionCatalog.REPORTS_DOCUMENTS_VIEW,
            PermissionCatalog.AUDIT_VIEW,
        ),
        critical = false,
        editable = false,
    )

    private fun readOnly(): RoleDefinition = role(
        code = SystemRoleCode.READ_ONLY.code,
        scope = RoleScope.ORGANIZATION,
        type = RoleType.ORGANIZATION,
        name = "Read Only",
        description = "Lectura general sin modificación de datos operativos ni configuración crítica.",
        permissionKeys = setOf(
            PermissionCatalog.ORGANIZATION_VIEW,
            PermissionCatalog.ORGANIZATION_MEMBERS_VIEW,
            PermissionCatalog.ACTIVITIES_VIEW,
            PermissionCatalog.BRANCHES_VIEW,
            PermissionCatalog.SETTINGS_BRANCHES_VIEW,
            PermissionCatalog.SETTINGS_EMISSION_POINTS_VIEW,
            PermissionCatalog.CATALOG_VIEW,
            PermissionCatalog.CATALOG_LOCAL_VIEW,
            PermissionCatalog.CUSTOMERS_VIEW,
            PermissionCatalog.SALES_VIEW,
            PermissionCatalog.PAYMENTS_VIEW,
            PermissionCatalog.RECEIVABLES_VIEW,
            PermissionCatalog.CASH_VIEW,
            PermissionCatalog.CASH_SESSION_VIEW_CURRENT,
            PermissionCatalog.CASH_SESSION_VIEW_HISTORY,
            PermissionCatalog.INVENTORY_VIEW,
            PermissionCatalog.DOCUMENTS_VIEW,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW,
            PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_LIST,
            PermissionCatalog.SIGNATURE_VIEW_METADATA,
            PermissionCatalog.REPORTS_DASHBOARD_VIEW,
            PermissionCatalog.REPORTS_SALES_VIEW,
            PermissionCatalog.REPORTS_CASH_VIEW,
            PermissionCatalog.REPORTS_DOCUMENTS_VIEW,
        ),
        critical = false,
        editable = false,
    )

    private fun organizationOwnerPermissions(): Set<String> = setOf(
        PermissionCatalog.CREDENTIALS_USERS_VIEW,
        PermissionCatalog.CREDENTIALS_USERS_CREATE,
        PermissionCatalog.CREDENTIALS_USERS_INVITE,
        PermissionCatalog.CREDENTIALS_USERS_RESET_PASSWORD,
        PermissionCatalog.CREDENTIALS_USERS_BLOCK,
        PermissionCatalog.CREDENTIALS_USERS_UNBLOCK,
        PermissionCatalog.CREDENTIALS_SESSIONS_REVOKE,
        PermissionCatalog.CREDENTIALS_ROLES_VIEW,
        PermissionCatalog.CREDENTIALS_ROLES_ASSIGN,
        PermissionCatalog.CREDENTIALS_ROLES_MANAGE,
        PermissionCatalog.ORGANIZATION_VIEW,
        PermissionCatalog.ORGANIZATION_UPDATE,
        PermissionCatalog.ORGANIZATION_UPDATE_PROFILE,
        PermissionCatalog.ORGANIZATION_MEMBERS_VIEW,
        PermissionCatalog.ORGANIZATION_MEMBERS_MANAGE,
        PermissionCatalog.BRANCHES_VIEW,
        PermissionCatalog.BRANCHES_CREATE,
        PermissionCatalog.BRANCHES_UPDATE,
        PermissionCatalog.SETTINGS_BRANCHES_VIEW,
        PermissionCatalog.SETTINGS_BRANCHES_MANAGE,
        PermissionCatalog.SETTINGS_EMISSION_POINTS_VIEW,
        PermissionCatalog.SETTINGS_EMISSION_POINTS_MANAGE,
        PermissionCatalog.ACTIVITIES_VIEW,
        PermissionCatalog.ACTIVITIES_CREATE,
        PermissionCatalog.ACTIVITIES_UPDATE,
        PermissionCatalog.CATALOG_VIEW,
        PermissionCatalog.CATALOG_LOCAL_VIEW,
        PermissionCatalog.CATALOG_LOCAL_COPY_FROM_MASTER,
        PermissionCatalog.CATALOG_LOCAL_UPDATE_LOCAL_COPY,
        PermissionCatalog.CATALOG_LOCAL_CHANGE_PRICE,
        PermissionCatalog.CATALOG_LOCAL_CHANGE_TAX_PROFILE,
        PermissionCatalog.CATALOG_LOCAL_DISABLE_LOCAL_COPY,
        PermissionCatalog.CATALOG_LOCAL_REQUEST_NEW_ITEM,
        PermissionCatalog.CATALOG_IDENTIFIERS_SCAN,
        PermissionCatalog.CATALOG_IDENTIFIERS_ADD_LOCAL,
        PermissionCatalog.CATALOG_UNITS_MANAGE_CONVERSIONS,
        PermissionCatalog.CUSTOMERS_VIEW,
        PermissionCatalog.CUSTOMERS_CREATE,
        PermissionCatalog.CUSTOMERS_UPDATE,
        PermissionCatalog.SALES_VIEW,
        PermissionCatalog.SALES_CREATE,
        PermissionCatalog.SALES_CONFIRM,
        PermissionCatalog.SALES_CANCEL,
        PermissionCatalog.SALES_CANCEL_AFTER_PAYMENT,
        PermissionCatalog.SALES_CLOSE,
        PermissionCatalog.SALES_APPLY_DISCOUNT,
        PermissionCatalog.SALES_ITEMS_CHANGE_STATUS,
        PermissionCatalog.PAYMENTS_VIEW,
        PermissionCatalog.PAYMENTS_COLLECT,
        PermissionCatalog.PAYMENTS_PARTIAL_COLLECT,
        PermissionCatalog.PAYMENTS_MARK_AS_CREDIT,
        PermissionCatalog.PAYMENTS_REFUND,
        PermissionCatalog.PAYMENTS_REVERSE,
        PermissionCatalog.RECEIVABLES_VIEW,
        PermissionCatalog.RECEIVABLES_CREATE,
        PermissionCatalog.RECEIVABLES_REGISTER_PAYMENT,
        PermissionCatalog.CASH_VIEW,
        PermissionCatalog.CASH_OPEN,
        PermissionCatalog.CASH_CLOSE,
        PermissionCatalog.CASH_SESSION_VIEW_CURRENT,
        PermissionCatalog.CASH_SESSION_VIEW_HISTORY,
        PermissionCatalog.CASH_SESSION_OPEN,
        PermissionCatalog.CASH_SESSION_CLOSE,
        PermissionCatalog.CASH_MOVEMENTS_REGISTER_INFLOW,
        PermissionCatalog.CASH_MOVEMENTS_REGISTER_OUTFLOW,
        PermissionCatalog.CASH_MOVEMENTS_ADJUST,
        PermissionCatalog.INVENTORY_VIEW,
        PermissionCatalog.INVENTORY_ADJUST,
        PermissionCatalog.DOCUMENTS_VIEW,
        PermissionCatalog.DOCUMENTS_GENERATE_INTERNAL_TICKET,
        PermissionCatalog.DOCUMENTS_GENERATE_PHYSICAL_SALE_NOTE_REGISTRY,
        PermissionCatalog.DOCUMENTS_ISSUE_ELECTRONIC_INVOICE,
        PermissionCatalog.DOCUMENTS_DOWNLOAD_PDF,
        PermissionCatalog.DOCUMENTS_DOWNLOAD_XML,
        PermissionCatalog.DOCUMENTS_INVOICE_ISSUE,
        PermissionCatalog.DOCUMENTS_INVOICE_DOWNLOAD_XML,
        PermissionCatalog.DOCUMENTS_INVOICE_DOWNLOAD_RIDE,
        PermissionCatalog.DOCUMENTS_INVOICE_REQUEST_CANCELLATION,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_LIST,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_ISSUE,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_RETRY,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_DOWNLOAD_XML,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_DOWNLOAD_RIDE,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_EMAIL,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW_ERRORS,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_VIEW_AUDIT,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_HOMOLOGATE,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_ENABLE_PRODUCTION,
        PermissionCatalog.DOCUMENTS_ELECTRONIC_INVOICE_MANAGE_SETTINGS,
        PermissionCatalog.TAX_MANAGE,
        PermissionCatalog.TAX_SETTINGS_VIEW,
        PermissionCatalog.TAX_SETTINGS_UPDATE_ORGANIZATION_REGIME,
        PermissionCatalog.TAX_PROFILES_ASSIGN_TO_ITEM,
        PermissionCatalog.SIGNATURE_VIEW_METADATA,
        PermissionCatalog.SIGNATURE_UPLOAD,
        PermissionCatalog.SIGNATURE_REPLACE,
        PermissionCatalog.SIGNATURE_REVOKE,
        PermissionCatalog.SIGNATURE_TEST,
        PermissionCatalog.SIGNATURE_USE_FOR_INVOICING,
        PermissionCatalog.SIGNATURE_VIEW_AUDIT,
        PermissionCatalog.REPORTS_DASHBOARD_VIEW,
        PermissionCatalog.REPORTS_SALES_VIEW,
        PermissionCatalog.REPORTS_CASH_VIEW,
        PermissionCatalog.REPORTS_TAX_VIEW,
        PermissionCatalog.REPORTS_DOCUMENTS_VIEW,
        PermissionCatalog.AUDIT_VIEW,
        PermissionCatalog.CATALOG_PRICE_VIEW,
        PermissionCatalog.CATALOG_PRICE_UPDATE,
        PermissionCatalog.CATALOG_PRICE_HISTORY_VIEW,
        PermissionCatalog.CATALOG_SEARCH_METADATA_VIEW,
        PermissionCatalog.CATALOG_SEARCH_METADATA_UPDATE,
        PermissionCatalog.CATALOG_PUBLIC_VISIBILITY_VIEW,
        PermissionCatalog.CATALOG_PUBLIC_VISIBILITY_UPDATE,
        PermissionCatalog.CATALOG_PUBLIC_VISIBILITY_HIDE,
        PermissionCatalog.CATALOG_PUBLIC_VISIBILITY_REPUBLISH,
        PermissionCatalog.CATALOG_PUBLIC_DISPLAY_UPDATE_PRICE_MODE,
        PermissionCatalog.CATALOG_PUBLIC_DISPLAY_UPDATE_STOCK_MODE,
        PermissionCatalog.CATALOG_PUBLIC_DISPLAY_ALLOW_COMPARISON,
        PermissionCatalog.CATALOG_PUBLIC_PREVIEW_VIEW,
        PermissionCatalog.BRANCH_LOCATION_VIEW,
        PermissionCatalog.BRANCH_LOCATION_UPDATE,
        PermissionCatalog.BRANCH_LOCATION_PUBLIC_VISIBILITY_VIEW,
        PermissionCatalog.BRANCH_LOCATION_PUBLIC_VISIBILITY_UPDATE,
        PermissionCatalog.BRANCH_LOCATION_PRIVACY_MODE_UPDATE,
        PermissionCatalog.DISCOVERY_SETTINGS_VIEW,
        PermissionCatalog.DISCOVERY_SETTINGS_UPDATE,
        PermissionCatalog.DISCOVERY_PREVIEW_VIEW,
        PermissionCatalog.DISCOVERY_AUDIT_VIEW,
        PermissionCatalog.BUSINESS_HOURS_VIEW,
        PermissionCatalog.BUSINESS_HOURS_UPDATE,
        PermissionCatalog.BUSINESS_HOURS_PUBLIC_VISIBILITY_UPDATE,
    )

    private fun organizationAdminPermissions(): Set<String> = organizationOwnerPermissions() - setOf(
        PermissionCatalog.PAYMENTS_REVERSE,
        PermissionCatalog.CASH_MOVEMENTS_ADJUST,
        PermissionCatalog.SIGNATURE_REVOKE,
        PermissionCatalog.CATALOG_PUBLIC_DISPLAY_ALLOW_COMPARISON,
    )

    private fun role(
        code: String,
        scope: RoleScope,
        type: RoleType,
        name: String,
        description: String,
        permissionKeys: Set<String>,
        critical: Boolean,
        editable: Boolean,
    ): RoleDefinition = RoleDefinition(
        id = "role_$code",
        code = code,
        organizationId = null,
        scope = scope,
        type = type,
        name = name,
        description = description,
        permissionKeys = permissionKeys,
        systemRole = true,
        critical = critical,
        editable = editable,
        status = RoleStatus.ACTIVE,
        schemaVersion = 1,
    )
}
