package com.hermes.infrastructure.mongo.id

enum class MongoIdPrefix(val value: String) {
    ORGANIZATION("org_"),
    BRANCH("br_"),
    EMISSION_POINT("emi_"),
    USER("usr_"),
    MEMBERSHIP("mem_"),
    ROLE("role_"),
    PLATFORM_CATALOG_FAMILY("fam_"),
    PLATFORM_CATALOG_TEMPLATE("tpl_"),
    ORGANIZATION_CATALOG_ITEM("item_"),
    CATALOG_REQUEST("catreq_"),
    CUSTOMER("cus_"),
    SALE("sale_"),
    RESERVATION("res_"),
    PAYMENT("pay_"),
    RECEIVABLE("recv_"),
    CASH_SESSION("cash_"),
    CASH_MOVEMENT("cmov_"),
    COMMERCIAL_DOCUMENT("doc_"),
    ELECTRONIC_PAYLOAD("epay_"),
    SRI_SUBMISSION("sri_"),
    TAX_PROFILE("taxp_"),
    TAX_RATE("taxr_"),
    SIGNATURE("sig_"),
    STOCK_BALANCE("stock_"),
    STOCK_MOVEMENT("stmov_"),
    AUDIT("audit_"),
    DOMAIN_EVENT("evt_"),
    OUTBOX_EVENT("out_"),
    MIGRATION("mig_"),
    HEALTH_CHECK("health_");
}
