package com.hermes.domain.payment

import com.hermes.domain.money.Money
import com.hermes.domain.shared.DomainRuleViolation
import java.time.Instant

/** Account receivable generated by credit/fiado or by remaining balance after partial payment. */
data class Receivable private constructor(
    val id: String,
    val organizationId: String,
    val branchId: String?,
    val saleId: String,
    val customerId: String?,
    val totalDue: Money,
    val paidAmount: Money,
    val dueAt: Instant?,
    val isVoided: Boolean,
    val isWrittenOff: Boolean,
    val createdAt: Instant,
    val updatedAt: Instant,
) {
    val balanceDue: Money
        get() = totalDue - paidAmount

    init {
        if (id.isBlank()) throw DomainRuleViolation("Receivable id cannot be blank.")
        if (organizationId.isBlank()) throw DomainRuleViolation("Receivable organization id cannot be blank.")
        if (saleId.isBlank()) throw DomainRuleViolation("Receivable sale id cannot be blank.")
        if (totalDue.amount.signum() <= 0) throw DomainRuleViolation("Receivable total due must be greater than zero.")
        if (paidAmount.currency != totalDue.currency) throw DomainRuleViolation("Receivable paid amount currency must match total due currency.")
        if (paidAmount > totalDue) throw DomainRuleViolation("Receivable paid amount cannot be greater than total due.")
        if (isVoided && isWrittenOff) throw DomainRuleViolation("Receivable cannot be voided and written off at the same time.")
    }

    fun status(now: Instant): CollectionStatus = CollectionStatusResolver.resolve(
        totalDue = totalDue,
        paidAmount = paidAmount,
        dueAt = dueAt,
        now = now,
        isVoided = isVoided,
        isWrittenOff = isWrittenOff,
    )

    fun registerCollection(amount: Money, collectedAt: Instant): Receivable {
        if (isVoided) throw DomainRuleViolation("Cannot collect a voided receivable.")
        if (isWrittenOff) throw DomainRuleViolation("Cannot collect a written-off receivable.")
        if (amount.amount.signum() <= 0) throw DomainRuleViolation("Collection amount must be greater than zero.")
        if (amount.currency != totalDue.currency) throw DomainRuleViolation("Collection currency must match receivable currency.")
        val newPaidAmount = paidAmount + amount
        if (newPaidAmount > totalDue) throw DomainRuleViolation("Collection amount cannot exceed receivable balance.")
        return copy(paidAmount = newPaidAmount, updatedAt = collectedAt)
    }

    fun writeOff(writtenOffAt: Instant): Receivable {
        if (paidAmount > Money.zero(totalDue.currency)) {
            throw DomainRuleViolation("Partially collected receivable cannot be written off without adjustment.")
        }
        if (isVoided) throw DomainRuleViolation("Voided receivable cannot be written off.")
        if (isWrittenOff) throw DomainRuleViolation("Receivable is already written off.")
        return copy(isWrittenOff = true, updatedAt = writtenOffAt)
    }

    fun void(voidedAt: Instant): Receivable {
        if (paidAmount > Money.zero(totalDue.currency)) {
            throw DomainRuleViolation("Collected receivable cannot be voided without reversal.")
        }
        if (isWrittenOff) throw DomainRuleViolation("Written-off receivable cannot be voided.")
        if (isVoided) throw DomainRuleViolation("Receivable is already voided.")
        return copy(isVoided = true, updatedAt = voidedAt)
    }

    companion object {
        fun createForSale(
            id: String,
            organizationId: String,
            saleId: String,
            customerId: String?,
            totalDue: Money,
            dueAt: Instant?,
            createdAt: Instant,
            branchId: String? = null,
        ): Receivable = Receivable(
            id = id.trim(),
            organizationId = organizationId.trim(),
            branchId = branchId?.trim()?.takeIf { it.isNotBlank() },
            saleId = saleId.trim(),
            customerId = customerId?.trim()?.takeIf { it.isNotBlank() },
            totalDue = totalDue,
            paidAmount = Money.zero(totalDue.currency),
            dueAt = dueAt,
            isVoided = false,
            isWrittenOff = false,
            createdAt = createdAt,
            updatedAt = createdAt,
        )

        fun restore(
            id: String,
            organizationId: String,
            branchId: String?,
            saleId: String,
            customerId: String?,
            totalDue: Money,
            paidAmount: Money,
            dueAt: Instant?,
            isVoided: Boolean,
            isWrittenOff: Boolean,
            createdAt: Instant,
            updatedAt: Instant,
        ): Receivable = Receivable(
            id = id.trim(),
            organizationId = organizationId.trim(),
            branchId = branchId?.trim()?.takeIf { it.isNotBlank() },
            saleId = saleId.trim(),
            customerId = customerId?.trim()?.takeIf { it.isNotBlank() },
            totalDue = totalDue,
            paidAmount = paidAmount,
            dueAt = dueAt,
            isVoided = isVoided,
            isWrittenOff = isWrittenOff,
            createdAt = createdAt,
            updatedAt = updatedAt,
        )
    }
}
